### ISSUE TITLE
ConcurrentModificationException in getOrMakePeer

### ISSUE THREAD

**Issue by jonathanraes** [Tribler/trustchain-android#54]
When dealing with ~10 peers or more, a concurrentmodification exception is sometimes thrown in getOrMakePeer when looping the peer list. 

```
06-19 15:36:41.152 6430-6454/nl.tudelft.cs4160.trustchain_android W/System.err: java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.next(ArrayList.java:831)
        at nl.tudelft.cs4160.trustchain_android.peer.PeerHandler.getOrMakePeer(PeerHandler.java:224)
        at nl.tudelft.cs4160.trustchain_android.network.MessageHandler.handleIntroductionResponse(MessageHandler.java:67)
06-19 15:36:41.153 6430-6454/nl.tudelft.cs4160.trustchain_android W/System.err:     at nl.tudelft.cs4160.trustchain_android.network.Network.handleMessage(Network.java:383)
        at nl.tudelft.cs4160.trustchain_android.network.Network.dataReceived(Network.java:360)
        at nl.tudelft.cs4160.trustchain_android.main.OverviewConnectionsActivity.lambda$startListenThread$3$OverviewConnectionsActivity(OverviewConnectionsActivity.java:409)
        at nl.tudelft.cs4160.trustchain_android.main.OverviewConnectionsActivity$$Lambda$3.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by jonathanraes** [comment]
The same exception occured
```         
at nl.tudelft.cs4160.trustchain_android.peer.PeerHandler.getEligiblePeer(PeerHandler.java:196)
```
This one is not caught in a catch block so crashes the app from the sendThread
